### ISSUE TITLE
Add 'possessive_suffix' method

### ISSUE THREAD

**Issue by elado** [dpbus/possessify#1]
``` ruby
"John".possessive_suffix # => "'s"
"James".possessive_suffix # => "'"
```

Sometimes you just want to render the suffix in a different container/html tag etc.

**Comment by dpbus** [comment]
Nice idea! I'll try to get to this today.

**Comment by dpbus** [comment]
Just cut version 1.1.0 of the gem with this change. Let me know if you have any issues!
